name: Check

on:
  push:
    branches:
      - master
    paths:
      - "**.py"

jobs:
  check:
    name: Check code
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}

      - name: Install deps (library & development)
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade flake8 pylint
          python -m pip install -r requirements.txt

      - name: Run flake8 current python versions
        run: python -m flake8 redpic tests setup.py

      - name: Run pylint current python versions
        run: python -m pylint redpic tests setup.py