name: Python Linter Checks

on:
  push:
    branches:
      - master
    paths:
      - "**.py"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}

      - name: Install deps (library & development)
        run: make deps

      - name: Run linters, formatters for current python versions
        run: make lint