name: Test

on:
  push:
    branches:
      - master
    paths:
      - "**.py"
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}

      - name: Install deps (library & development)
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pytest
          python -m pip install -r requirements.txt

      - name: Run functional test
        run: python -m pytest tests/functional/src